### PR TITLE
Fixes #22 : permit to load rutorrent settings

### LINKED ISSUE #22: [Proposal] Find a way to import Rutorrent settings inside the container
Hi,

I think it would be cool and useful to be able to import/mount our own Rutorrent settings folder inside the rtorrent-rutorrent container.

In that way, it will be possible to launch a new container with everything loaded and ready to use.
This mount should be available for both cases : with a Webroot and without.

I wanted to create a PR about this but I'm struggling with the command `mv /var/www/html/torrent` inside the [startup script](https://github.com/xataz/dockerfiles/blob/master/rtorrent-rutorrent/rootfs/usr/local/bin/startup)..

### PR DESCRIPTION
**Pull request by Djamy**
PR to try to resolve issue #22 

Do not merge without reviewing it !!

We probably need to discuss this. 

Isn't better to make a symlink instead of the `cp` [here](https://github.com/xataz/dockerfiles/compare/master...Djamy:master#diff-abba5c4b234a66bfc1c2b4479a01bdfaR16) and [here](https://github.com/xataz/dockerfiles/compare/master...Djamy:master#diff-abba5c4b234a66bfc1c2b4479a01bdfaR24) ?

And, I should probably update the README to explain how it works..

### CODE REVIEW

**Comment by xataz** [comment]
Hi Djamy,

Can you upgrade README.md with your update ?

XataZ

**Comment by Djamy** [comment]
Hi,

Sure! I'll do that later today. 
What do you think about the symlink instead of the copy ? Should I keep the copy or replace it by a symlink ?

**Comment by Djamy** [comment]
I'll try to finish this PR this weekend.

**Comment by xataz** [comment]
Commit #13f142c close this PR

**Pull request closed without merging**
